{"name": "Проверка передачи почты, которая уже используется ", "status": "passed", "description": "При запросе передается уже существующая почта", "start": 1725449749938, "stop": 1725449751790, "uuid": "14932149-387d-4bce-bb57-b62e14979bf2", "historyId": "c2e9d4b8273d24a2532c183cb3b684cb", "testCaseId": "c2e9d4b8273d24a2532c183cb3b684cb", "fullName": "test_update_user.TestUpdateUser#test_update_user_authorized_user_existent_email_error", "labels": [{"name": "suite", "value": "test_update_user"}, {"name": "subSuite", "value": "TestUpdateUser"}, {"name": "host", "value": "DESKTOP-6NP8JLT"}, {"name": "thread", "value": "38292-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_update_user"}]}